### ISSUE TITLE
undefined method `reduce'

### ISSUE THREAD

**Issue by jjk-jacky** [jekyll/classifier-reborn#26]
I'm using jekyll (2.5.1) and after upgrading ruby-classifier-reborn to 2.0.2 it errors out:
Error: undefined method `reduce' for #GSL::Vector...

I have no idea where this comes from, all I can tell is in 2.0.2 a few commits have replaced sum with .reduce(0, :+) (926fc3f8 & 555d4a3a) and that might to be the source of this. I've downgraded ruby-classifier-reborn back to 2.0.1 for now.

FYI I have ruby-rb-gsl 1.16.0.3 & gsl 1.16 (on Arch Linux x64)
